source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'faker'
gem 'haml-rails'
gem 'therubyracer'
gem 'less-rails-bootstrap'

group :development do
  gem 'spring'
end

group :development, :test do
  gem 'capybara'
  gem 'pry', :require => 'pry'
  gem 'rspec-rails'
  gem 'database_cleaner'
end
